### ISSUE TITLE
Security Rules Engine

### ISSUE THREAD

**Issue by curphey** [openraven/open-raven#2]
Add a security rules engine that has two core features

- Describe security conditions that can become security configuration and or security monitoring rules. 
- Manage rules

**Comment by curphey** [comment]
@mike-m-andrews  is gonna write up the proposed rule format / language in an RFC. Jason will own the rules management, although thats included in the RFC. @kickroot do we want to move this into a specific issue and create Rook ?

**Comment by kickroot** [comment]
We should break up into the following issues:

- Rules Specification
- Rules Repository Specification
- Rook

Each will build upon its predecessor.

**Comment by curphey** [comment]
And move that to the Magpie repo ?

**Comment by curphey** [comment]
Moved roadmap to magpie repo
